name: movement
channels:
  - defaults # Order matters tried defaults first
  - conda-forge
dependencies:
  - python>=3.6
  - ipython=7.8.0
  - jupyter=1.0.0
  - numpy=1.21.0
  - pandas=1.2.4
  - scipy=1.6.2
  - matplotlib=3.4.2
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - pip=19.1.1=py37_0
  - pyyaml=5.2
  - rasterio=1.2.6
  # - networkx=2.5.1
  - pycairo=1.20.1
  - python-igraph=0.9.1
  - sympy=1.8
  - pytables=3.6.1
  - pip:                            # Packages installed from PyPI
    - arviz==0.6.1
    - theano==1.0.4
    - jedi==0.17.2
  - pymc3=3.7
  #   - geopandas==0.6.2
